# Generated by Django 5.1.6 on 2025-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
