# Generated by Django 5.1.6 on 2025-03-20 10:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_game_excerpt_alter_game_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='exit', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
